# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNTUO5FkldKD_wbnD2xya6SA-HQnokMA
"""



import llm_abul_coaching

from llm_abul_coaching import get_qa_chain, create_vector_db

import streamlit as st

st.title('Abul Coaching FAQ')

question=st.text_input('Ask a question')

btn = st.button("Create Knowledgebase")
if btn:
    create_vector_db()
if question:
  chain=get_qa_chain()
  result=chain(question)
  st.write(result['result'])
  st.header('Answer')
  st.write(result['result'])



