# -*- coding: utf-8 -*-
"""llm_abul_teaching

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNTUO5FkldKD_wbnD2xya6SA-HQnokMA
"""

import subprocess

subprocess.run(["pip", "install", "-r", "/content/requirement.txt"])

pip install pyngrok

from pyngrok import ngrok
!ngrok update

import os
from threading import Thread

from google.colab import userdata
key=userdata.get('authotoken_key')

ngrok.set_auth_token(key)

def run_streamlit():
    # Change the port if 8501 is already in use or if you prefer another port
    os.system('streamlit run /content/app.py --server.port 8501')

# Start a thread to run the Streamlit app
thread = Thread(target=run_streamlit)
thread.start()

# Open a tunnel to the streamlit port 8501
public_url = ngrok.connect(8501)
print('Your Streamlit app is live at:', public_url)